type SchemaType = {
  blockchains: string[];
  full_name: string;
  id: string;
  namespace: string;
  table_name: string;
  __typename: string;
};

export type TableAttributeType = {
  blockchains: string[];
  column_name: string;
  data_type: string;
  full_name: string;
  id: string;
};

export const duneApiKey =
  'eyJraWQiOiJOU0tDc093eWNEYmc2UDcwb1pcL3lMKzY1NFwvUUhKK0pFVkxISkpWRWtiSlE9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIxMTljYTMxZS02MDcwLTRlMWItOWE5MS05MWZiZTQwMjIzM2EiLCJldmVudF9pZCI6ImNkMmNlMzZmLTM0OTMtNDIwYS05ODkwLTFlNGQ3ZTFjMWM0ZCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE2NzgzMzI2MDEsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS13ZXN0LTEuYW1hem9uYXdzLmNvbVwvZXUtd2VzdC0xX0h5Q1kzc3RoZSIsImV4cCI6MTY3OTMwMjIwMiwiaWF0IjoxNjc5MzAxOTAyLCJqdGkiOiJkYWNlYzQxNy05ZTczLTQ3ZDYtODhhZS1mNjZkNGRlZjQ0ZDAiLCJjbGllbnRfaWQiOiI0M2FjYW1yN2IydWVvamdwZ290djNiajZ1bCIsInVzZXJuYW1lIjoidGhhbmd0biJ9.GJqX6LS__xJJx-d3zpGiSjR-QK7I7RxidRxAxA--7QZEXYYbKMFqCh9nMkpHDxBVa3IU7PpmHoxkNBKzdJo6y7rGylrg1Mfqyg7WcwZPkBItoEB9oxSWlFioJbgDLGQZeifmWx3KcUCchiHvMS4RpOjlHRLf_hEmWRwpAMAfP81Ocg_kHxdtu_f3bWpy0hRKwenqgX6Tu_E4jCeaYIuwY97WJp1ikNSOKkOKAEc-I61XQMhkYbAMDvnzzClNysmqPfAUoM1fWSAwcXEkEXOJAreAg_YkV7Pe8OazZX-U1t3FXTm_4K3LV0-mvYXcw3oZwyXrbaSOLlmj0uavH47tdQ';

export const schemas: SchemaType[] = [
  {
    id: '11.arbitrum.blocks.difficulty.3bc56c',
    namespace: 'arbitrum',
    table_name: 'blocks',
    full_name: 'arbitrum.blocks',
    blockchains: ['arbitrum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.arbitrum.creation_traces.address.51d7e8',
    namespace: 'arbitrum',
    table_name: 'creation_traces',
    full_name: 'arbitrum.creation_traces',
    blockchains: ['arbitrum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.arbitrum.logs.tx_hash.9c29fb',
    namespace: 'arbitrum',
    table_name: 'logs',
    full_name: 'arbitrum.logs',
    blockchains: ['arbitrum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.arbitrum.logs_decoded.namespace.d98435',
    namespace: 'arbitrum',
    table_name: 'logs_decoded',
    full_name: 'arbitrum.logs_decoded',
    blockchains: ['arbitrum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.arbitrum.traces.trace_address.e6be59',
    namespace: 'arbitrum',
    table_name: 'traces',
    full_name: 'arbitrum.traces',
    blockchains: ['arbitrum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.arbitrum.traces_decoded.function_name.4fd4c9',
    namespace: 'arbitrum',
    table_name: 'traces_decoded',
    full_name: 'arbitrum.traces_decoded',
    blockchains: ['arbitrum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.arbitrum.transactions.max_fee_per_gas.b16bb7',
    namespace: 'arbitrum',
    table_name: 'transactions',
    full_name: 'arbitrum.transactions',
    blockchains: ['arbitrum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.avalanche_c.blocks.miner.367f73',
    namespace: 'avalanche_c',
    table_name: 'blocks',
    full_name: 'avalanche_c.blocks',
    blockchains: ['avalanche_c'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.avalanche_c.creation_traces.code.4e0b77',
    namespace: 'avalanche_c',
    table_name: 'creation_traces',
    full_name: 'avalanche_c.creation_traces',
    blockchains: ['avalanche_c'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.avalanche_c.logs.data.1faa8a',
    namespace: 'avalanche_c',
    table_name: 'logs',
    full_name: 'avalanche_c.logs',
    blockchains: ['avalanche_c'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.avalanche_c.logs_decoded.tx_hash.a1b3b9',
    namespace: 'avalanche_c',
    table_name: 'logs_decoded',
    full_name: 'avalanche_c.logs_decoded',
    blockchains: ['avalanche_c'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.avalanche_c.traces.code.b7f119',
    namespace: 'avalanche_c',
    table_name: 'traces',
    full_name: 'avalanche_c.traces',
    blockchains: ['avalanche_c'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.avalanche_c.traces_decoded.to.cc0c1d',
    namespace: 'avalanche_c',
    table_name: 'traces_decoded',
    full_name: 'avalanche_c.traces_decoded',
    blockchains: ['avalanche_c'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.avalanche_c.transactions.gas_limit.d48d44',
    namespace: 'avalanche_c',
    table_name: 'transactions',
    full_name: 'avalanche_c.transactions',
    blockchains: ['avalanche_c'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bitcoin.blocks.difficulty.cb5935',
    namespace: 'bitcoin',
    table_name: 'blocks',
    full_name: 'bitcoin.blocks',
    blockchains: ['bitcoin'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bitcoin.inputs.spent_output_number.508cb8',
    namespace: 'bitcoin',
    table_name: 'inputs',
    full_name: 'bitcoin.inputs',
    blockchains: ['bitcoin'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bitcoin.outputs.block_date.35a980',
    namespace: 'bitcoin',
    table_name: 'outputs',
    full_name: 'bitcoin.outputs',
    blockchains: ['bitcoin'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bitcoin.transactions.virtual_size.ca0d9c',
    namespace: 'bitcoin',
    table_name: 'transactions',
    full_name: 'bitcoin.transactions',
    blockchains: ['bitcoin'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bnb.blocks.total_difficulty.c9f91b',
    namespace: 'bnb',
    table_name: 'blocks',
    full_name: 'bnb.blocks',
    blockchains: ['bnb'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bnb.creation_traces.from.e8b51f',
    namespace: 'bnb',
    table_name: 'creation_traces',
    full_name: 'bnb.creation_traces',
    blockchains: ['bnb'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bnb.logs.topic2.33a499',
    namespace: 'bnb',
    table_name: 'logs',
    full_name: 'bnb.logs',
    blockchains: ['bnb'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bnb.logs_decoded.block_time.6543e9',
    namespace: 'bnb',
    table_name: 'logs_decoded',
    full_name: 'bnb.logs_decoded',
    blockchains: ['bnb'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bnb.traces.input.4fbe28',
    namespace: 'bnb',
    table_name: 'traces',
    full_name: 'bnb.traces',
    blockchains: ['bnb'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bnb.traces_decoded.namespace.a871f7',
    namespace: 'bnb',
    table_name: 'traces_decoded',
    full_name: 'bnb.traces_decoded',
    blockchains: ['bnb'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.bnb.transactions.hash.36f4a3',
    namespace: 'bnb',
    table_name: 'transactions',
    full_name: 'bnb.transactions',
    blockchains: ['bnb'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.ethereum.blocks.gas_limit.055159',
    namespace: 'ethereum',
    table_name: 'blocks',
    full_name: 'ethereum.blocks',
    blockchains: ['ethereum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.ethereum.creation_traces.tx_hash.514f2e',
    namespace: 'ethereum',
    table_name: 'creation_traces',
    full_name: 'ethereum.creation_traces',
    blockchains: ['ethereum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.ethereum.logs.block_number.65c051',
    namespace: 'ethereum',
    table_name: 'logs',
    full_name: 'ethereum.logs',
    blockchains: ['ethereum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.ethereum.logs_decoded.contract_name.f58945',
    namespace: 'ethereum',
    table_name: 'logs_decoded',
    full_name: 'ethereum.logs_decoded',
    blockchains: ['ethereum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.ethereum.traces.gas.769733',
    namespace: 'ethereum',
    table_name: 'traces',
    full_name: 'ethereum.traces',
    blockchains: ['ethereum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.ethereum.traces_decoded.block_date.0403ed',
    namespace: 'ethereum',
    table_name: 'traces_decoded',
    full_name: 'ethereum.traces_decoded',
    blockchains: ['ethereum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.ethereum.transactions.block_time.e2f994',
    namespace: 'ethereum',
    table_name: 'transactions',
    full_name: 'ethereum.transactions',
    blockchains: ['ethereum'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.fantom.blocks.hash.d4b2a0',
    namespace: 'fantom',
    table_name: 'blocks',
    full_name: 'fantom.blocks',
    blockchains: ['fantom'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.fantom.creation_traces.block_time.3cae08',
    namespace: 'fantom',
    table_name: 'creation_traces',
    full_name: 'fantom.creation_traces',
    blockchains: ['fantom'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.fantom.logs.data.572fa5',
    namespace: 'fantom',
    table_name: 'logs',
    full_name: 'fantom.logs',
    blockchains: ['fantom'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.fantom.logs_decoded.contract_address.43704d',
    namespace: 'fantom',
    table_name: 'logs_decoded',
    full_name: 'fantom.logs_decoded',
    blockchains: ['fantom'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.fantom.traces.output.e0128b',
    namespace: 'fantom',
    table_name: 'traces',
    full_name: 'fantom.traces',
    blockchains: ['fantom'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.fantom.traces_decoded.trace_address.543406',
    namespace: 'fantom',
    table_name: 'traces_decoded',
    full_name: 'fantom.traces_decoded',
    blockchains: ['fantom'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.fantom.transactions.block_number.d845a6',
    namespace: 'fantom',
    table_name: 'transactions',
    full_name: 'fantom.transactions',
    blockchains: ['fantom'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.gnosis.blocks.hash.5b366b',
    namespace: 'gnosis',
    table_name: 'blocks',
    full_name: 'gnosis.blocks',
    blockchains: ['gnosis'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.gnosis.creation_traces.address.216615',
    namespace: 'gnosis',
    table_name: 'creation_traces',
    full_name: 'gnosis.creation_traces',
    blockchains: ['gnosis'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.gnosis.logs.data.6464a0',
    namespace: 'gnosis',
    table_name: 'logs',
    full_name: 'gnosis.logs',
    blockchains: ['gnosis'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.gnosis.logs_decoded.namespace.8c0fcf',
    namespace: 'gnosis',
    table_name: 'logs_decoded',
    full_name: 'gnosis.logs_decoded',
    blockchains: ['gnosis'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.gnosis.traces.block_number.4a483c',
    namespace: 'gnosis',
    table_name: 'traces',
    full_name: 'gnosis.traces',
    blockchains: ['gnosis'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.gnosis.traces_decoded.namespace.541a18',
    namespace: 'gnosis',
    table_name: 'traces_decoded',
    full_name: 'gnosis.traces_decoded',
    blockchains: ['gnosis'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.gnosis.transactions.max_fee_per_gas.28dbaa',
    namespace: 'gnosis',
    table_name: 'transactions',
    full_name: 'gnosis.transactions',
    blockchains: ['gnosis'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.goerli.blocks.miner.e8bd08',
    namespace: 'goerli',
    table_name: 'blocks',
    full_name: 'goerli.blocks',
    blockchains: ['goerli'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.goerli.creation_traces.block_time.89477b',
    namespace: 'goerli',
    table_name: 'creation_traces',
    full_name: 'goerli.creation_traces',
    blockchains: ['goerli'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.goerli.logs.topic3.426831',
    namespace: 'goerli',
    table_name: 'logs',
    full_name: 'goerli.logs',
    blockchains: ['goerli'],
    __typename: 'arrakis_schemas',
  },
  {
    id: '11.goerli.logs_decoded.namespace.865a50',
    namespace: 'goerli',
    table_name: 'logs_decoded',
    full_name: 'goerli.logs_decoded',
    blockchains: ['goerli'],
    __typename: 'arrakis_schemas',
  },
];

export const tableDetail: TableAttributeType[] = [
  {
    blockchains: ['arbitrum'],
    column_name: 'access_list',
    data_type: 'array(row(address varbinary,storageKeys array(varbinary)))',
    full_name: 'arbitrum.transactions',
    id: '11.arbitrum.transactions.access_list.285327',
  },
  {
    blockchains: ['arbitrum'],
    column_name: 'block_hash',
    data_type: 'varbinary',
    full_name: 'arbitrum.transactions',
    id: '11.arbitrum.transactions.block_hash.9c6d44',
  },
  {
    blockchains: ['arbitrum'],
    column_name: 'from',
    data_type: 'varbinary',
    full_name: 'arbitrum.transactions',
    id: '11.arbitrum.transactions.from.b1f70e',
  },
  {
    blockchains: ['arbitrum'],
    column_name: 'gas_price',
    data_type: 'uint256',
    full_name: 'arbitrum.transactions',
    id: '11.arbitrum.transactions.gas_price.dbfd4e',
  },
];

export const columns = [
  'time',
  'number',
  'gas_limit',
  'gas_used',
  'difficulty',
  'total_difficulty',
  'size',
  'base_fee_per_gas',
  'hash',
  'parent_hash',
  'miner',
  'nonce',
];

export const columnsDemo = [
  {
    Header: 'col1',
    accessor: 'col1',
  },
  {
    Header: 'col2',
    accessor: 'col2',
  },
];

export const columnsData = columns.map((col) => ({
  Header: col,
  accessor: col,
}));
export const queryValueData = [
  {
    base_fee_per_gas: null,
    difficulty: 0,
    gas_limit: '287962567',
    gas_used: '3736',
    hash: '0xf6a372f74d764bef2d9b6c538868a72086deb01b38c63eda3c0bc57988e2c8a1',
    miner: '0x0000000000000000000000000000000000000000',
    nonce: '0x0000000000000000',
    number: 80499,
    parent_hash:
      '0xe3a2cc02585585ad429c93d2b67aee29b25669a982554b9e6606b1f611a5789d',
    size: 1320,
    time: '2021-07-08 11:06:58.000 UTC',
    total_difficulty: '0',
  },

  {
    base_fee_per_gas: null,
    difficulty: 0,
    gas_limit: '287990722',
    gas_used: '3736',
    hash: '0xc03ae520338918e7cd652f26bc07b735dbb20dad4b6b03ccb95a13f1d3ce328a',
    miner: '0x0000000000000000000000000000000000000000',
    nonce: '0x0000000000000000',
    number: 14587,
    parent_hash:
      '0x3a51cb8429ee0e33b59b8e8d0cca28069ccaec875b50235b43d38157a3a15d13',
    size: 1318,
    time: '2021-06-23 00:00:35.000 UTC',
    total_difficulty: '0',
  },
];
